repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix']

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
    -   id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
        -   eslint
        -   eslint-config-standard
        -   eslint-plugin-import
        -   eslint-plugin-node
        -   eslint-plugin-promise 